# Generated by Django 4.1.5 on 2023-01-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip', models.CharField(max_length=6)),
                ('query', models.TextField()),
            ],
        ),
    ]
